[package]
name = "terminal_chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
colored = "2"

[dependencies.nokhwa]
version = "0.9.4"
features = ["input-msmf"]